badType = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=FATIGUE",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583fab-5b63391f193bd63b3df4efe6",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "FATIGUE"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "GET",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7i1he2IAMESyQ=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:37:15 +0000",
        "timeEpoch": 1649950635582,
    },
    "isBase64Encoded": False,
}

postNoBody = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=FATIGUE",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "29",
        "content-type": "application/json",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583fab-20ecd8f5377c1e49117397c6",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "FATIGUE"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "POST",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7i2jhlIAMESZQ=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:37:15 +0000",
        "timeEpoch": 1649950635650,
    },
    "isBase64Encoded": False,
}
