options = {
    "version": "2.0",
    "routeKey": "ANY /springs_backend",
    "rawPath": "/springs_backend",
    "rawQueryString": "CALCULATION=FATIGUE",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625999ed-53536db84de190c21ffe250d",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "FATIGUE"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "bsthlri5j1",
        "domainName": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "bsthlri5j1",
        "http": {
            "method": "OPTIONS",
            "path": "/springs_backend",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QoT9LiO0oAMEJEg=",
        "routeKey": "ANY /springs_backend",
        "stage": "$default",
        "time": "15/Apr/2022:16:14:37 +0000",
        "timeEpoch": 1650039277733,
    },
    "isBase64Encoded": False,
}


post = {
    "version": "2.0",
    "routeKey": "ANY /springs_backend",
    "rawPath": "/springs_backend",
    "rawQueryString": "CALCULATION=FATIGUE",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "153",
        "content-type": "application/json",
        "host": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625999ed-13412c4b63589c3773b18f45",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "FATIGUE"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "bsthlri5j1",
        "domainName": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "bsthlri5j1",
        "http": {
            "method": "POST",
            "path": "/springs_backend",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QoT9MgzyoAMEJyA=",
        "routeKey": "ANY /springs_backend",
        "stage": "$default",
        "time": "15/Apr/2022:16:14:37 +0000",
        "timeEpoch": 1650039277800,
    },
    "body": '{"material":"Hard-drawn wire (ASTM No. A227)","endType":"Plain","wireDiameter_in":552,"OD_in":122,"L0_in":331,"Ls_in":1112,"F_max_lbf":11,"F_min_lbf":22}',
    "isBase64Encoded": False,
}
