options = {
    "version": "2.0",
    "routeKey": "ANY /springs_backend",
    "rawPath": "/springs_backend",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625999e6-7df4f488657a7faa3332f037",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "bsthlri5j1",
        "domainName": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "bsthlri5j1",
        "http": {
            "method": "OPTIONS",
            "path": "/springs_backend",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QoT7_hRYIAMEJ8g=",
        "routeKey": "ANY /springs_backend",
        "stage": "$default",
        "time": "15/Apr/2022:16:14:30 +0000",
        "timeEpoch": 1650039270179,
    },
    "isBase64Encoded": False,
}


post = {
    "version": "2.0",
    "routeKey": "ANY /springs_backend",
    "rawPath": "/springs_backend",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "123",
        "content-type": "application/json",
        "host": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "origin": "http://localhost:8080",
        "referer": "http://localhost:8080/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625999e6-2dbf502314e1119601f31c54",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "bsthlri5j1",
        "domainName": "bsthlri5j1.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "bsthlri5j1",
        "http": {
            "method": "POST",
            "path": "/springs_backend",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QoT8DihPIAMEJ-Q=",
        "routeKey": "ANY /springs_backend",
        "stage": "$default",
        "time": "15/Apr/2022:16:14:30 +0000",
        "timeEpoch": 1650039270518,
    },
    "body": '{"material":"Hard-drawn wire (ASTM No. A227)","endType":"Plain","wireDiameter_in":552,"OD_in":122,"L0_in":331,"Ls_in":1112}',
    "isBase64Encoded": False,
}
