options = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583f8f-71b0aa3a10cc2337671d7252",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "OPTIONS",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7egjJMoAMESQA=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:36:47 +0000",
        "timeEpoch": 1649950607844,
    },
    "isBase64Encoded": False,
}

post = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "135",
        "content-type": "application/json",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583f90-312eba29427e517526d81ff6",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "POST",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7ekixooAMESWQ=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:36:48 +0000",
        "timeEpoch": 1649950608226,
    },
    "body": '{"material":"Hard-drawn wire (ASTM No. A227)","endType":"Plain and ground","wireDiameter_mm":123,"OD_mm":313,"L0_mm":12312,"Ls_mm":123}',
    "isBase64Encoded": False,
}
