options = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625876ce-4f1f1cad06b42b3632d1dcdf",
        "x-forwarded-for": "69.174.157.222",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "OPTIONS",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "69.174.157.222",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QleAUglboAMEVQg=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:19:32:30 +0000",
        "timeEpoch": 1649964750676,
    },
    "isBase64Encoded": False,
}


post = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=MAIN",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "138",
        "content-type": "application/json",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-625876ce-25658dd641d6d3c241488177",
        "x-forwarded-for": "69.174.157.222",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "MAIN"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "POST",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "69.174.157.222",
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "QleAXiZboAMEVPA=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:19:32:30 +0000",
        "timeEpoch": 1649964750991,
    },
    "body": '{"material":"Chrome-vanadium wire (ASTM No. A232)","endType":"Plain and ground","wireDiameter_mm":123,"OD_mm":321,"L0_mm":123,"Ls_mm":321}',
    "isBase64Encoded": False,
}
