options = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=STATIC",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "access-control-request-headers": "content-type",
        "access-control-request-method": "POST",
        "content-length": "0",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583f96-058dcb29343fd84b7fe7e0c5",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "STATIC"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "OPTIONS",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7fmhd7oAMESHQ=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:36:54 +0000",
        "timeEpoch": 1649950614857,
    },
    "isBase64Encoded": False,
}

post = {
    "version": "2.0",
    "routeKey": "ANY /attempt1_python",
    "rawPath": "/attempt1_python",
    "rawQueryString": "CALCULATION=STATIC",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.5",
        "content-length": "12",
        "content-type": "application/json",
        "host": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "origin": "http://springs.nicolasfransen.com",
        "referer": "http://springs.nicolasfransen.com/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "sec-gpc": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        "x-amzn-trace-id": "Root=1-62583f96-4a044f717a9635546c6c7146",
        "x-forwarded-for": "128.210.106.73",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
    },
    "queryStringParameters": {"CALCULATION": "STATIC"},
    "requestContext": {
        "accountId": "350905604366",
        "apiId": "vhdufpz2ne",
        "domainName": "vhdufpz2ne.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "vhdufpz2ne",
        "http": {
            "method": "POST",
            "path": "/attempt1_python",
            "protocol": "HTTP/1.1",
            "sourceIp": "128.210.106.73",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0",
        },
        "requestId": "Qk7fnheBoAMESHQ=",
        "routeKey": "ANY /attempt1_python",
        "stage": "$default",
        "time": "14/Apr/2022:15:36:54 +0000",
        "timeEpoch": 1649950614928,
    },
    "body": '{"Fs_N":212}',
    "isBase64Encoded": False,
}
